export { default as Logo } from "./Logo/Logo"
export { default as Cover } from "./Cover/Cover"
export { default as Quote } from "./Quote/Quote"
export { default as Brides } from "./Brides/Brides"
export { default as Detail } from "./Detail/Detail"
export { default as Gallery } from "./Gallery/Gallery"
export { default as Rsvp } from "./Rsvp/Rsvp"
export { default as Wish } from "./Wish/Wish"